[package]
name = "tabcel"
version = "0.1.0"
authors = ["Emil <emil.donkersloot@online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#crossterm = "0.20"
termion = "1.5"
tui = "0.16"